#!/bin/bash
clear
fun_logo(){
cat << EOF
          +---------------------------------+
          | INSTALLER VPS-NEW FREE OFFICIAL |
          |     CREATED BY @Trator_777      |  
          +---------------------------------+
EOF
}
meu_ip(){
MIP=$(ip addr | grep 'inet' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)
if [[ $MIP = "127.0.0.1" ]]; then
MIP=$(wget -qO- ipv4.icanhazip.com)
elif [[ ! $MIP ]]; then
MIP=$(wget -qO- ipv4.icanhazip.com)
fi
echo "$MIP"
}

echo -e "LOADING..."
apt-get install figlet -y >/dev/null 2>&1 && figlet VPS-NEW
fun_logo

Basic="menu PGet.py uports.sh usercodes sockspy.sh POpen.py PPriv.py PPub.py PDirect.py utils.sh dropbear.sh apacheon.sh openvpn.sh shadowsocks.sh squid.sh"
LINK="https://github.com/GNULinux2632042stab1404x8664/VPS-NEW-Manager/blob/master/BASE-SCRIPT.zip?raw=true"
TEMP="$HOME/$RANDOM" && [[ ! -d ${TEMP} ]] && mkdir ${TEMP}
SCPdir="/etc/nhvps" && [[ ! -d ${SCPdir} ]] && mkdir ${SCPdir}
SCPusr="${SCPdir}/main-user" && [[ ! -d ${SCPusr} ]] && mkdir ${SCPusr}
SCPfrm="/etc/main-frm" && [[ ! -d ${SCPfrm} ]] && mkdir ${SCPfrm}
SCPinst="/etc/main-inst" && [[ ! -d ${SCPinst} ]] && mkdir ${SCPinst}
SCPidioma="${SCPdir}/idioma"

apt-get install screen -y >/dev/null 2>&1 && echo -e "${COLOR[0]}SCREEN OK"
apt-get install zip -y >/dev/null 2>&1 && echo -e "UNZIP OK"
apt-get install nano -y >/dev/null 2>&1 && echo -e "NANO OK"
apt-get install php -y >/dev/null 2>&1 && echo -e "PHP OK"
apt-get install jq -y >/dev/null 2>&1 && echo -e "JQ OK"
sudo apt-get python -y >/dev/null 2>&1
apt-get install unzip -y >/dev/null 2>&1 && echo -e "PROCESSING DOWLOAD"
apt-get python3 -y >/dev/null 2>&1
wget ${LINK} -O $HOME/ADM -o /dev/null && echo -e "EXTRACTING FILES ${COLOR[3]}"
cd ${TEMP} && unzip $HOME/ADM && echo -e "${COLOR[0]}SUCCESSFUL EXTRACTION!"

echo -e "${COLOR[0]}INSTALLING..."
echo -ne "${COLOR[3]}["

for arq in `ls ${TEMP}`; do
echo -ne "${COLOR[1]}X" && sleep 0.2s
case $arq in
"squid.sh")mv -f ${TEMP}/$arq ${SCPinst}/$arq && chmod +x ${SCPinst}/$arq;;
"dropbear.sh")mv -f ${TEMP}/$arq ${SCPinst}/$arq && chmod +x ${SCPinst}/$arq;;
"openvpn.sh")mv -f ${TEMP}/$arq ${SCPinst}/$arq && chmod +x ${SCPinst}/$arq;;
"shadowsocks.sh")mv -f ${TEMP}/$arq ${SCPinst}/$arq && chmod +x ${SCPinst}/$arq;;
"sockspy.sh")mv -f ${TEMP}/$arq ${SCPinst}/$arq && chmod +x ${SCPinst}/$arq;;
"PDirect.py")mv -f ${TEMP}/$arq ${SCPinst}/$arq && chmod +x ${SCPinst}/$arq;;
"PGet.py")mv -f ${TEMP}/$arq ${SCPinst}/$arq && chmod +x ${SCPinst}/$arq;;
"POpen.py")mv -f ${TEMP}/$arq ${SCPinst}/$arq && chmod +x ${SCPinst}/$arq;;
"PPriv.py")mv -f ${TEMP}/$arq ${SCPinst}/$arq && chmod +x ${SCPinst}/$arq;;
"PPub.py")mv -f ${TEMP}/$arq ${SCPinst}/$arq && chmod +x ${SCPinst}/$arq;;
"uports.sh")mv -f ${TEMP}/$arq ${SCPinst}/$arq && chmod +x ${SCPinst}/$arq;;
"apacheon.sh")mv -f ${TEMP}/$arq ${SCPfrm}/$arq && chmod +x ${SCPfrm}/$arq;;
"utils.sh")mv -f ${TEMP}/$arq ${SCPinst}/$arq && chmod +x ${SCPinst}/$arq;;
"usercodes")mv -f ${TEMP}/$arq ${SCPusr}/$arq && chmod +x ${SCPusr}/$arq;;
*)mv -f ${TEMP}/$arq ${SCPdir}/$arq && chmod +x ${SCPdir}/$arq;;
esac
done && rm -rf ${TEMP}
echo -e "${COLOR[3]}]"

cat << EOF > /bin/vps
#!/bin/bash
cd ${SCPdir} && ./menu
EOF
chmod +x /bin/vps

rm $HOME/ADM > /dev/null 2>&1
rm $HOME/$0  > /dev/null 2>&1


echo -e "${COLOR[0]}INSTALLATION SUCCESSFUL!"
echo -e "WRITE THE FOLLOWING COMMANDS: ${COLOR[1]} vps \033[0m"
